# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fb103097eb16a8fc3fc415557dc21cd4ec70dceaf3d82e8b8545bdd166d9d62c7925f50ea41a795c29ed32e95459a2a5ec2484fc8aaf08e510287e029f72ea9

test:
  secret_key_base: 591836433ca95e06d9c5408a89b09832e66d6ff8f6aa65e5e7d8ec41408df69cb177b63778a07d1ee9e114fa9f9a400b0cfe9c0e5060f463cdf022f997028fec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
